# Generated by Django 5.2.13 on 2026-05-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_watch_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='description',
        ),
    ]
