upstream gunicorn_servers {
    server 127.0.0.1:8000;
}

server {
    listen 8080;
    server_name localhost;
    
    location /public {
        alias /home/aida/2026-MAI-Backend-A-Mashrabova/lab2/public;
        autoindex on;
    }
    
    location /gunicorn {
        proxy_pass http://gunicorn_servers;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
